name: compat-pr
run-name: compat-pr [${{ inputs.target_sha }}]

on:
  workflow_dispatch:
    inputs:
      target_repo:
        required: true
      target_sha:
        required: true
      comment_pr_number:
        required: true

jobs:
  suite:
    uses: ./.github/workflows/suite.yml
    with:
      target_repo: ${{ inputs.target_repo }}
      target_sha: ${{ inputs.target_sha }}

  summary:
    if: ${{ always() }}
    needs: suite
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: compat-*
          merge-multiple: true
          path: .artifacts
      - id: publish
        continue-on-error: true
        env:
          RESULTS_BRANCH: pr-${{ inputs.comment_pr_number }}
        run: |
          commit=$(cargo run --quiet -- update-baseline \
            --branch "${RESULTS_BRANCH}" \
            --source-dir .artifacts | tail -n1)
          echo "results_branch=${RESULTS_BRANCH}" >> "$GITHUB_OUTPUT"
          echo "results_commit=${commit}" >> "$GITHUB_OUTPUT"
      - run: >
          cargo run --quiet -- pr-comment
          --target-repo "${{ inputs.target_repo }}"
          --target-sha "${{ inputs.target_sha }}"
          --run-url "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          --comment-repo "wasmerio/wasmer"
          --comment-pr-number "${{ inputs.comment_pr_number }}"
          --github-token "${{ secrets.WASMER_REPO_GH_TOKEN }}"
          --results-branch "${{ steps.publish.outputs.results_branch }}"
          --results-commit "${{ steps.publish.outputs.results_commit }}"
      - if: ${{ steps.publish.outcome == 'failure' }}
        run: exit 1
